DATA:
  name: "CIFAR10"
  img_size: 32
  num_classes: 10
RUN:
  save_sample_gradients: False
MODEL:
  backbone: "deep_conv"
  g_conv_dim: "N/A"
  d_conv_dim: "N/A"
  ensemble: True
  ens_multiplier: 10
  ens_weighting: "rand_bernoulli"
  ens_split_batch: True
OPTIMIZATION:
  d_updates_per_step: 2
  batch_size: 640
  total_steps: 200000
