DATA:
  name: "CIFAR10"
  img_size: 32
  num_classes: 10
RUN:
  save_sample_gradients: True
MODEL:
  ensemble: True
  ens_multiplier: 3
  ens_weighting: "rand_bernoulli"
  ens_split_batch: True
LOSS:
  adv_loss: "wasserstein"
  apply_gp: True
  gp_lambda: 10.0
OPTIMIZATION:
  batch_size: 192
