DATA:
  name: "CIFAR10"
  img_size: 32
  num_classes: 10
RUN:
  save_sample_gradients: True
MODEL:
  ensemble: True
  ens_multiplier: 5
  ens_weighting: "ew"
  ens_grad_norm: True
LOSS:
  adv_loss: "wasserstein"
  apply_gp: True
  gp_lambda: 10.0
OPTIMIZATION:
  total_steps: 150000
