DATA:
  name: "CIFAR10"
  img_size: 32
  num_classes: 10
RUN:
  save_sample_gradients: True
MODEL:
  ensemble: True
  ens_multiplier: 3
  ens_weighting: "soft"
LOSS:
  adv_loss: "wasserstein"
  apply_gp: False
  gp_lambda: 0.0
