DATA:
  name: "Tiny_ImageNet"
  img_size: 64
  num_classes: 200
RUN:
  save_sample_gradients: False
MODEL:
  ensemble: True
  ens_multiplier: 1
  ens_weighting: "ew"
LOSS:
  adv_loss: "wasserstein"
  apply_gp: True
  gp_lambda: 10.0
OPTIMIZATION:
  total_steps: 150000
